### ISSUE TITLE
Tojan in example 23B

### ISSUE THREAD

**Issue by pigmin** [Hardi-St/MobaLedLib#1]
Hi.

You got a virus in the file Prog_Generator_MobaLedLib.xlsm

Virus name : Trojan.GenericKD.32730496

**Comment by Hardi-St** [comment]
**Hi pigmin,**

thank you for the feedback.

This is a false alarm generated by the antivirus software which detects that the excel vba macro generates cmd files and executes them which is a protentional risk.

There is no vicious code in the program. You can check this on your own by inspecting the code with ALT+F11. In addition, you could upload the program to an internet virus scan portal. 
I did this, when I got the first report, because the program could have been infected on its way through the web. 

**=> The excel programs are clean.**

Hardi
